### PR TITLE
Unit test 

### LINKED ISSUE #123: Organization Routes - Unit Test
Organization_test.go: PostgreSQL Test Suite for Organization Operations

This test suite validates all CRUD operations for the Organization entity using a PostgreSQL database. The tests cover:

- TestCreateOrganization: Ensures organizations can be successfully created with proper data validation, password hashing, and persistence.

- TestGetOrganization: Verifies that organizations can be retrieved by email address with all fields correctly populated.

- TestUpdateOrganization: Tests partial updates to organization details while maintaining unchanged fields.

- TestUpdateOrganizationWithPassword: Specifically tests password updates, ensuring passwords are properly hashed and not stored in plaintext.

- TestDeleteOrganization: Confirms organizations can be deleted from the system.

- TestLoginOrganization: Validates the authentication flow with correct credentials returns proper user data and authentication tokens.

- TestLoginOrganizationInvalidPassword: Verifies authentication fails with incorrect password.

- TestLoginOrganizationInvalidEmail: Ensures authentication fails for non-existent organizations.

- TestGetNonExistentOrganization: Validates proper error handling when attempting to retrieve organizations that don't exist.

- TestInvalidOrganizationData: Tests error handling when invalid data is submitted.

Each test properly cleans up after execution to ensure test isolation.

### LINKED ISSUE #124: Application Routes - Unit test
Application_test.go: PostgreSQL Test Suite for Application Management

This test suite validates the complete application lifecycle in the volunteer management system using PostgreSQL. The tests cover:

- TestCreateApplication: Validates that volunteers can successfully apply for opportunities with proper validation and persistence.

- TestGetAllApplications: Ensures the system can retrieve all applications across the platform.

- TestGetApplicationByID: Verifies individual applications can be accessed by their unique ID with all relevant data.

- TestGetApplicationsByVolunteerID: Tests filtering applications by volunteer, enabling volunteers to view their application history.

- TestGetApplicationsByOpportunityID: Validates filtering applications by opportunity, allowing organizations to review all applicants.

- TestGetApplicationsByStatus: Confirms applications can be filtered by status (pending, accepted, rejected), supporting workflow management.

- TestUpdateApplication: Ensures applications can be updated, particularly for status changes during the review process.

- TestDeleteApplication: Verifies applications can be removed from the system when necessary.

- TestGetNonExistentApplication: Tests proper error handling for non-existent application lookups.

- TestInvalidApplicationData: Validates error handling for malformed application submissions.

All tests maintain proper database state between executions through careful cleanup processes.

### LINKED ISSUE #125: Category Routes - Unit test
Category_test.go: PostgreSQL Test Suite for Volunteer Categories

This test suite validates the management of volunteer opportunity categories using PostgreSQL. The tests cover:

- TestCreateCategory: Ensures the system can initialize with a predefined set of volunteering categories.

- TestGetCategories: Verifies that all categories can be retrieved for display in the UI.

- TestCreateCategoryIdempotence: Confirms that the category creation process is idempotent, preventing duplicate categories when the initialization process runs multiple times.

- TestCategoryDatabaseError: Validates proper error handling when database operations fail.

These tests ensure that the categorization system functions correctly, providing a consistent taxonomy for classifying volunteer opportunities across the platform.

### LINKED ISSUE #126: Opportunity Routes - Unit test
Opportunity_test.go: PostgreSQL Test Suite for Volunteer Opportunities

This test suite validates all operations related to volunteer opportunities using PostgreSQL. The tests cover:

- TestCreateOpportunity: Ensures organizations can create new volunteer opportunities with proper validation and persistence.

- TestGetOpportunity: Verifies that opportunities can be retrieved by ID with all data correctly populated.

- TestUpdateOpportunity: Tests the ability to modify opportunity details such as title, description, and requirements.

- TestDeleteOpportunity: Confirms opportunities can be removed from the system when they're no longer available.

- TestGetNonExistentOpportunity: Tests proper error handling when attempting to access non-existent opportunities.

- TestInvalidOpportunityData: Validates error handling for malformed opportunity submissions.

These tests ensure the core functionality of posting, retrieving, updating, and removing volunteer opportunities works correctly, forming the foundation of the opportunity marketplace.

### PR DESCRIPTION
**Pull request by NikhilDinesan11**
Closes #123 
Closes #124 
Closes #125 
Closes #126

### CODE REVIEW

**Review by Dhruv-mak — CHANGES_REQUESTED** [review]
@NikhilDinesan11 Fix this Issues:
image
image

File: backend/routes/Organization_test.go [hunk 1]
```diff
@@ -0,0 +1,452 @@
...
+	userMap, exists := response["user"]
+	assert.True(t, exists, "Response should contain user data")
+	
+	// Check user details if it exists
+	if exists {
+		user, ok := userMap.(map[string]interface{})
+		assert.True(t, ok, "User should be a JSON object")
+		
+		if ok {
+			assert.Equal(t, organization.Email, user["Email"])
```
Comment (Dhruv-mak) [inline backend/routes/Organization_test.go]: Rename `user["Email"]` to `user["email"]`.

File: backend/routes/Organization_test.go [hunk 2]
```diff
@@ -0,0 +1,452 @@
...
+			assert.Equal(t, organization.Name, user["Name"])
```
Comment (Dhruv-mak) [inline backend/routes/Organization_test.go]: rename `user["Name"]` with `user["name"]`

**Review by Dhruv-mak — CHANGES_REQUESTED** [review]

File: backend/routes/Organization_test.go (hunk 2 above)
Comment (NikhilDinesan11) [reply backend/routes/Organization_test.go]: I have fixed it...can you please check it now

**Comment by NikhilDinesan11** [comment]
Fixes #139

**Review by Dhruv-mak — APPROVED** [review]

**Review by prathamrao021 — APPROVED** [review]
